### ISSUE TITLE
Bootstrap con Sass

### ISSUE THREAD

**Issue by fernando-gomez** [UNIZAR-30226-2021-06/settlers-of-banambitha#2]
Desarrollando la barra de navegación y la barra de los amigos, dentro de mi rama, me he puesto a instalar Bootstrap porque tenía cosas interesantes, para hacer mas fácil el hacerlas, pero **bootstrap** se mueve con _css_, entonces no se si deberíamos cambiar a _css_ para que fuera mejor la integración o si ya lo habéis usado y solucionado, ya que no se si por ejemplo **material** también usa _css_ en vez de _sass_. Además porque al instalar las librerías de **bootstrap** me salen inconsistencias en el código y no compila.

He visto alguna opción online pero no se si me termina de convencer.
@jaimecb @AnyielFernandes

**Comment by AnyielFernandes** [comment]
En principio Sass es un compilador que genera código css, así que no debería haber problemas de compatibilidad. Todos los ejemplos que encuentro de material están en css, no he tenido problemas al traducirlos a Sass. Mira los imports, cada elemento que utilices lo tendrás que importar en el módulo de angular, y en los ficheros Sass igual tienes que añadir algún import para según qué cosas.
